tasks:
    - name: Install and build
      init: npm i -g pnpm && pnpm i --shamefully-hoist
    - name: Start web server
      command: npm run start

ports:
     - port: 3000
        onOpen: open-browser
