name: Build & Deploy to Github Pages

on:
  push:
  repository_dispatch:
  workflow_dispatch:

# Don't forget to set up the github pages to point to the `gh-pages` branch!

jobs:
  node-to-gh:
    runs-on: ubuntu-latest
    name: Build & Deploy to Github Pages
    steps:
      - id: node-to-gh
        run: |
          npm list gh-pages || npm i -g gh-pages
          npm ci
          gh-pages -d src -t ${{ secrets.t }}
