name: Build and Deploy
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on:
  workflow_dispatch:
  push:
  repository_dispatch:
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Install Packages📡
          run: |
                npm list pnpm || npm i pnpm -g
                echo ::set-env name=FOO::$(pnpm store path)
                pnpm add https://github.com/FreshPenguin112/theia-pnpm#master
                rm -rf node_modules && rm -rf ${{ env.FOO }} && pnpm update && pnpm install --save && theia --save
        - name: Generate Static Site🛠
          run: |
                 webpack --bail
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            publish_branch: gh-pages
            allow_empty_commit: true
